### ISSUE TITLE
The  "you missing changelog!" message should be customizable

### ISSUE THREAD

**Issue by JAremko** [peterjgrainger/action-changelog-reminder#27]
It would be really cool if there was a way to modify the "you missing changelog!" message. For example, I would  like to add a link to the changelog file and contributing guidelines ([something like here](https://circleci.com/gh/syl20bnr/spacemacs/50041?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)) :thinking:

**Comment by peterjgrainger** [comment]
Sounds like a great option! Thanks for the input
