### ISSUE TITLE
Does it work for PRs from forks?

### ISSUE THREAD

**Issue by JAremko** [peterjgrainger/action-changelog-reminder#28]
[I tried running it in my fork](https://github.com/JAremko/spacemacs-pr/pull/14) and it worked but it doesn't seem to work for PRs from forks.

[Example](https://github.com/syl20bnr/spacemacs/pull/13063) and [This is how error looks like]( https://github.com/syl20bnr/spacemacs/pull/13063/checks?check_run_id=348855014)

**Comment by peterjgrainger** [comment]
Not sure about forks... I'll have a look, thanks for giving me an example

**Comment by peter-grainger** [comment]
Confirmed. It's an issue. I think it's because when you merge a fork the PR is in the repository you forked from.  I'll have a look if this is possible with the Github actions token.

**Comment by JAremko** [comment]
@peter-grainger  You probably can run cron jobs + use https://developer.github.com/v3/pulls/#list-pull-requests-files as a workaround. But it's kinda meh since the reaction to PR will be delayed :thinking:

**Comment by peterjgrainger** [comment]
@JAremko I think this is the same problem https://github.community/t5/GitHub-Actions/GitHub-Action-workflow-is-executed-for-a-PR-from-a-forked-repo/m-p/29579

I see why they would do this. You don't want people forking your repo to have full write access to your issues. Not sure there is a way around it :(

**Comment by JAremko** [comment]
Yeah not with actions.  :thinking:

**Comment by peterjgrainger** [comment]
For anyone looking at this later other actions have the same problem with forks. Maybe at some point they will sort out the permissions. Here is a discussion on the labeller action https://github.com/actions/labeler/issues/12

**Comment by aprilmintacpineda** [comment]
Still open, was this ever resolved?

**Comment by peterjgrainger** [comment]
Yes. You can now configure this!
