### ISSUE TITLE
Feature request: Delete comment after the Changelog was updated

### ISSUE THREAD

**Issue by pocman** [peterjgrainger/action-changelog-reminder#83]
Hi, 
thanks a lot for this action !

Could it be possible to delete the existing reminding comment if the changelog was updated after the comment was posted ?

**Comment by peterjgrainger** [comment]
Sounds reasonable.

I'll have a look when I get a chance.

**Comment by peterjgrainger** [comment]
@pocman v1.3.0 should sort this. Sorry for the delay in getting this sorted I forgot about it :s
